Release: snapshot from tag 0.12
Co-authored-by: Akshay Viswanathan <vis.akshay@gmail.com>
Co-authored-by: albitoft-amd <albin.toft@amd.com>
Co-authored-by: alcoholfreebear <shuyi.li@amd.com>
Co-authored-by: amd-sbhol <SpandanKumar.Bhol@amd.com>
Co-authored-by: Bo <bo.zhang2@amd.com>
Co-authored-by: Brednas <Sander.BijldeVroe@amd.com>
Co-authored-by: Daniel Wärnå <daniel.warna@amd.com>
Co-authored-by: haakanpersson <hakan.persson@amd.com>
Co-authored-by: Jonathan Saylor <jonathan.saylor@amd.com>
Co-authored-by: Juho Kerttula <juho.kerttula@amd.com>
Co-authored-by: Jussi Elo <jussi.elo@amd.com>
Co-authored-by: Mark van Heeswijk <mark.vanheeswijk@amd.com>
Co-authored-by: mholopai-amd <215145032+mholopai-amd@users.noreply.github.com>
Co-authored-by: Miikael Leskinen <miikael.leskinen@amd.com>
Co-authored-by: Mika Ranta <Mika.Ranta@amd.com>
Co-authored-by: mvilenius-amd <mvileniu@amd.com>
Co-authored-by: Nate Overton-Katz <noverton@amd.com>
Co-authored-by: negautam <negautam@amd.com>
Co-authored-by: ravindra2208 <rkannoji@amd.com>
Co-authored-by: rsampaio-amd <rui.sampaio@amd.com>
Co-authored-by: Sebastian Remander <sebastian.remander@amd.com>
Co-authored-by: Strahinja Stamenkovic <strahinja.stamenkovic@amd.com>
Co-authored-by: Stanislau Fink <stanislau.fink@amd.com>
Co-authored-by: tkarkkai-amd <tkarkkai@amd.com>

diff --git a/docker/Dockerfile.aim b/docker/Dockerfile.aim
--- a/docker/Dockerfile.aim
+++ b/docker/Dockerfile.aim
@@ -4,18 +4,18 @@
 
 # ARGs before FROM are used in the FROM instruction
 # these must be overridden via --build-arg
-ARG BASE_REGISTRY_NAMESPACE=dummy_base_registry
-ARG BASE_REPOSITORY=dummy_base_repository
-ARG BASE_TAG=dummy_base_tag
-FROM ${BASE_REGISTRY_NAMESPACE}/${BASE_REPOSITORY}:${BASE_TAG} AS final
+ARG PARENT_REGISTRY_PREFIX=dummy_parent_registry_prefix
+ARG PARENT_REPOSITORY=dummy_parent_repository
+ARG PARENT_TAG=dummy_parent_tag
+FROM ${PARENT_REGISTRY_PREFIX}/${PARENT_REPOSITORY}:${PARENT_TAG} AS final
 
 # Re-declare ARGs after FROM to use them in subsequent instructions
-ARG BASE_REGISTRY_NAMESPACE
-ARG BASE_REPOSITORY
-ARG BASE_TAG
+ARG PARENT_REGISTRY_PREFIX
+ARG PARENT_REPOSITORY
+ARG PARENT_TAG
 ARG ORG
 ARG MODEL
-ARG ACCELERATOR_TYPE
+ARG ACCELERATOR_FAMILY
 
 # Validate required build arguments
 RUN test -n "${ORG}" || (echo "ERROR: ORG build arg is required and cannot be empty" && exit 1)
@@ -23,7 +23,7 @@ RUN test -n "${MODEL}" || (echo "ERROR: MODEL build arg is required and cannot b
 
 # Set environment variables
 # AIM_ID identifies this as a model-specific AIM container
-ENV AIM_BASE_IMAGE_REF=${BASE_REGISTRY_NAMESPACE}/${BASE_REPOSITORY}:${BASE_TAG}
+ENV AIM_BASE_IMAGE_REF=${PARENT_REGISTRY_PREFIX}/${PARENT_REPOSITORY}:${PARENT_TAG}
 ENV AIM_ID=${ORG}/${MODEL}
 ENV AIM_ALLOW_GENERAL_PROFILE_FALLBACK="false"
 
@@ -31,6 +31,23 @@ RUN echo "AIM Base Image: ${AIM_BASE_IMAGE_REF}"
 RUN echo "AIM ID: ${AIM_ID}"
 
 # Copy model-specific profiles
-COPY assets/${ACCELERATOR_TYPE}/${ORG}/${MODEL}/profiles /workspace/aim-runtime/profiles/${ORG}/${MODEL}/
+COPY assets/${ACCELERATOR_FAMILY}/${ORG}/${MODEL}/profiles /workspace/aim-runtime/profiles/${ORG}/${MODEL}/
+
+# Check if the LICENSE file is present in the workspace (if ACCELERATOR_FAMILY is epyc also check for LICENSE.EPYC_AIMS)
+# If not found, exit with error
+RUN if [ "$ACCELERATOR_FAMILY" = "epyc" ]; then \
+        if [ -f "/workspace/LICENSE.EPYC_AIMS" ]; then \
+            echo "LICENSE.EPYC_AIMS file found"; \
+        else \
+            echo "ERROR: LICENSE.EPYC_AIMS file not found"; \
+            exit 1; \
+        fi; \
+        if [ -f "/workspace/LICENSE" ]; then \
+            echo "LICENSE file found"; \
+        else \
+            echo "ERROR: LICENSE file not found"; \
+            exit 1; \
+        fi; \
+    fi
 
 ENTRYPOINT ["./entrypoint.py"]
